key_filename: ./key.txt
nonce1: !!binary |
  cjszRTAbHw51iTyzUVb/3A==
nonce2: !!binary |
  WariPxaw4zJstXvl/uV5xg==
tag1: !!binary |
  Tc+SJxOp1oOZgIcwDBom+g==
tag2: !!binary |
  p3Jfx1bx/PvsEbzh1w3AkQ==
value_filename: ./val.txt
