key_filename: ./key.txt
nonce1: !!binary |
  yKJVhG0s9d7fz/D+iK4v0g==
nonce2: !!binary |
  ZJBH8sUcJiwbMZeXCbRmWg==
tag1: !!binary |
  kYuYJZYLabHWck2Nj3M3Xw==
tag2: !!binary |
  QyrB+rjHPQfFF+CnWZ3pRA==
value_filename: ./val.txt
