key_filename: ./key.txt
nonce1: !!binary |
  Xj7sMNcvKNBXVh5oXcQShA==
nonce2: !!binary |
  g4aWOIuhCltBOISori9lHg==
tag1: !!binary |
  V6bbLdDYtExhug7PlUcw3g==
tag2: !!binary |
  zL31+mFp223/GN+qHi5ECA==
value_filename: ./val.txt
