key_filename: ./key.txt
nonce1: !!binary |
  4Ikfub2bwFhL2jk30+pBLQ==
nonce2: !!binary |
  RPd0wjzPL7V0TNBYlaOcnQ==
tag1: !!binary |
  u9boIWlOQgtsMS4uUpyT8Q==
tag2: !!binary |
  C/pPhF5+OglsowrSoajszg==
value_filename: ./val.txt
